__init__.py:
  NAME: Home
  ICON: ğŸ 
  DESCRIPTION: Welcome to my app!

statistical_tests:
  __init__.py:
    NAME: Statistical Tests
    ICON: ğŸ”¢
    DESCRIPTION: Perform several statistical tests!
    SIDEBAR: radio
    TAG: ğŸ“š Statistics

  ab_test.py:
    NAME: A/B
    ICON: ğŸ†
    DESCRIPTION: Perform A/B test!
    TAG: ğŸ”¢ Statistical Tests

  chi2_test.py:
    NAME: Chi-squared
    ICON: ğŸ†‡
    DESCRIPTION: Perform chi-squared test!
    TAG: ğŸ”¢ Statistical Tests

  t-test.py:
    NAME: T-test
    ICON: ğŸ†ƒ
    DESCRIPTION: Perform t-test!
    TAG: ğŸ”¢ Statistical Tests

dimensionality_reduction:
  __init__.py:
    NAME: Dimensionality Reduction
    ICON: ğŸ”½
    DESCRIPTION: Reduce dimensionality for high-D data!
    SIDEBAR: radio
    TAG: ğŸ“š Statistics

  pca.py:
    NAME: PCA
    ICON: â­•
    DESCRIPTION: Principal Component Analysis
    TAG: ğŸ”½ Dimensionality Reduction

  t-sne.py:
    NAME: t-SNE
    ICON: ğŸ“Š
    DESCRIPTION: t-distributed Stochastic Neighbor Embedding
    TAG: ğŸ”½ Dimensionality Reduction

landmarks:
  __init__.py:
    NAME: Landmarks
    ICON: ğŸ“
    DESCRIPTION: Perform live landmark detection using Mediapipe!
    SIDEBAR: radio
    TAG: ğŸ‘ï¸ Computer Vision

  face_landmarks.py:
    NAME: Face Mesh
    ICON: ğŸ‘¤
    DESCRIPTION: Face landmark detection
    TAG: ğŸ“ Landmarks

  pose_landmarks.py:
    NAME: Pose Landmarks
    ICON: ğŸ¤¸â€â™‚ï¸
    DESCRIPTION: Body pose landmark detection
    TAG: ğŸ“ Landmarks

object_detection:
  __init__.py:
    NAME: Object Detection
    ICON: ğŸ”
    DESCRIPTION: Detect objects via your webcam!
    SIDEBAR: radio
    TAG: ğŸ‘ï¸ Computer Vision

  face_detection.py:
    NAME: Face Detection
    ICON: ğŸ‘€
    DESCRIPTION: Detection of one or several faces
    TAG: ğŸ” Object Detection
  
  multi_objects.py:
    NAME: Multi-Object Detection
    ICON: ğŸ“¦
    DESCRIPTION: Detection 80+ different objects
    TAG: ğŸ” Object Detection

image_generation:
  __init__.py:
    NAME: Image Generation
    ICON: ğŸ¨
    DESCRIPTION: Generate pictures with AI!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  dall_e.py:
    NAME: DALLÂ·E
    ICON: ğŸ–¼ï¸
    DESCRIPTION: DALLÂ·E model from OpenAI
    TAG: ğŸ¨ Image Generation

  stable_diffusion.py:
    NAME: Stable Diffusion
    ICON: ğŸ–¼ï¸
    DESCRIPTION: Stable Diffusion model from Stability AI
    TAG: ğŸ¨ Image Generation

large_language_models:
  __init__.py:
    NAME: Large Language Models
    ICON: ğŸ’¬
    DESCRIPTION: Interact with large language models!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  chatbot.py:
    NAME: Basic Chatbot
    ICON: ğŸ‘‹
    DESCRIPTION: A regular chatbot.
    TAG: ğŸ¤– Chatbots

  chatbot_rag.py:
    NAME: Chatbot with RAG
    ICON: ğŸ“„
    DESCRIPTION: A chatbot with RAG (retrieval augmented generation).
    TAG: ğŸ¤– Chatbots

  chatbot_tools.py:
    NAME: Chatbot with Tools
    ICON: ğŸ› ï¸
    DESCRIPTION: A chatbot augmented with tools (web access, code interpreter, etc.)
    TAG: ğŸ¤– Chatbots

  chatbot_web_summary.py:
    NAME: Webpage summary
    ICON: ğŸŒ
    DESCRIPTION: A model to synthetize to text content of a webpage.
    TAG: ğŸ”„ Other
