__init__.py:
  NAME: "Home"
  ICON: "ğŸ "
  DESCRIPTION: "Welcome to my app!"

action_recognition:
  __init__.py:
    NAME: Action Recognition
    ICON: ğŸ‹ï¸
    DESCRIPTION: Perform action recognition using a classifier!
    TAG: ğŸ‘ï¸ Computer Vision

image_generation:
  __init__.py:
    NAME: Image Generation
    ICON: ğŸ¨
    DESCRIPTION: Generate pictures with AI!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  dall_e.py:
    NAME: DALLÂ·E
    ICON: ğŸ–¼ï¸
    DESCRIPTION: DALLÂ·E model from OpenAI

  stable_diffusion.py:
    NAME: Stable Diffusion
    ICON: ğŸ–¼ï¸
    DESCRIPTION: Stable Diffusion model from Stability AI

landmarks_detection:
  __init__.py:
    NAME: Landmarks Detection
    ICON: ğŸ¯
    DESCRIPTION: Detect face and body pose landmarks!
    TAG: ğŸ‘ï¸ Computer Vision

  face_landmarks.py:
    NAME: Face Landmarks
    ICON: ğŸ‘¤ğŸ“
    DESCRIPTION: Face landmarker

  pose_landmarks.py:
    NAME: Pose Landmarks
    ICON: ğŸ¤¸â€â™‚ï¸ğŸ“
    DESCRIPTION: Body pose landmarker

large_language_models:
  __init__.py:
    NAME: Large Language Models
    ICON: ğŸ’¬
    DESCRIPTION: Chat with large language models!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  chatbot.py:
    NAME: Chatbot
    ICON: ğŸ¤–
    DESCRIPTION: A regular chatbot.

  chatbot_rag.py:
    NAME: Chatbot RAG
    ICON: ğŸ¤–ğŸ“„
    DESCRIPTION: A chatbot with RAG (retrieval augmented generation).

  chatbot_tools.py:
    NAME: Chatbot Tools
    ICON: ğŸ¤–ğŸ› ï¸
    DESCRIPTION: A chatbot augmented with tools (web access, code interpreter, etc.)
