__init__.py:
  NAME: "Home"
  ICON: "ğŸ "
  DESCRIPTION: "Welcome to my app!"

landmarks:
  __init__.py:
    NAME: Landmarks
    ICON: ğŸ“
    DESCRIPTION: Perform landmark detection using Mediapipe!
    SIDEBAR: radio
    TAG: ğŸ‘ï¸ Computer Vision

  face_landmarks.py:
    NAME: Face Mesh
    ICON: ğŸ‘¤
    DESCRIPTION: Face landmark detection
    TAG: ğŸ“ Landmarks

  pose_landmarks.py:
    NAME: Pose Landmarks
    ICON: ğŸ¤¸â€â™‚ï¸
    DESCRIPTION: Body pose landmark detection
    TAG: ğŸ“ Landmarks

image_generation:
  __init__.py:
    NAME: Image Generation
    ICON: ğŸ¨
    DESCRIPTION: Generate pictures with AI!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  dall_e.py:
    NAME: DALLÂ·E
    ICON: ğŸ–¼ï¸
    DESCRIPTION: DALLÂ·E model from OpenAI
    TAG: ğŸ¨ Image Generation

  stable_diffusion.py:
    NAME: Stable Diffusion
    ICON: ğŸ–¼ï¸
    DESCRIPTION: Stable Diffusion model from Stability AI
    TAG: ğŸ¨ Image Generation

object_detection:
  __init__.py:
    NAME: Object Detection
    ICON: ğŸ”
    DESCRIPTION: Detect objects via your webcam!
    SIDEBAR: radio
    TAG: ğŸ‘ï¸ Computer Vision

  face_detection.py:
    NAME: Face Detection
    ICON: ğŸ‘€
    DESCRIPTION: Detection of one or several faces
    TAG: ğŸ” Object Detection

large_language_models:
  __init__.py:
    NAME: Large Language Models
    ICON: ğŸ’¬
    DESCRIPTION: Chat with large language models!
    SIDEBAR: radio
    TAG: ğŸ§  Generative AI

  chatbot.py:
    NAME: Basic Chatbot
    ICON: ğŸ‘‹
    DESCRIPTION: A regular chatbot.
    TAG: ğŸ¤– Chatbots

  chatbot_rag.py:
    NAME: Chatbot with RAG
    ICON: ğŸ“„
    DESCRIPTION: A chatbot with RAG (retrieval augmented generation).
    TAG: ğŸ¤– Chatbots

  chatbot_tools.py:
    NAME: Chatbot with Tools
    ICON: ğŸ› ï¸
    DESCRIPTION: A chatbot augmented with tools (web access, code interpreter, etc.)
    TAG: ğŸ¤– Chatbots

  chatbot_web_summary.py:
    NAME: Webpage summary
    ICON: ğŸŒ
    DESCRIPTION: A model to synthetize to text content of a webpage.
    TAG: ğŸ”„ Other
